<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-31 02:32
=======
# Generated by Django 4.0.3 on 2022-03-31 06:34
>>>>>>> e9b79c0306fc3d484eb26c877a860da22cbc501d

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
=======
                ('quantity', models.IntegerField()),
                ('productcolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolor')),
>>>>>>> e9b79c0306fc3d484eb26c877a860da22cbc501d
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
