# Generated by Django 4.0.3 on 2022-03-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productcolor',
            new_name='product_color',
        ),
    ]
